"""
Table of strings which marshal streams refer to by index.

Copied from MARSHAL_STRINGS in src/Marshal.cpp of the blue library
(https://github.com/carbonengine/blue).

blue is distributed under the MIT license:

    MIT License

    Copyright (c) 2026 CCP Games

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
"""

STRINGS = (
    b'*corpid',
    b'*locationid',
    b'age',
    b'Asteroid',
    b'authentication',
    b'ballID',
    b'beyonce',
    b'bloodlineID',
    b'capacity',
    b'categoryID',
    b'character',
    b'characterID',
    b'characterName',
    b'characterType',
    b'charID',
    b'chatx',
    b'clientID',
    b'config',
    b'contraband',
    b'corporationDateTime',
    b'corporationID',
    b'createDateTime',
    b'customInfo',
    b'description',
    b'divisionID',
    b'DoDestinyUpdate',
    b'dogmaIM',
    b'EVE System',
    b'flag',
    b'foo.SlimItem',
    b'gangID',
    b'Gemini',
    b'gender',
    b'graphicID',
    b'groupID',
    b'header',
    b'idName',
    b'invbroker',
    b'itemID',
    b'items',
    b'jumps',
    b'line',
    b'lines',
    b'locationID',
    b'locationName',
    b'macho.CallReq',
    b'macho.CallRsp',
    b'macho.MachoAddress',
    b'macho.Notification',
    b'macho.SessionChangeNotification',
    b'modules',
    b'name',
    b'objectCaching',
    b'objectCaching.CachedObject',
    b'OnChatJoin',
    b'OnChatLeave',
    b'OnChatSpeak',
    b'OnGodmaShipEffect',
    b'OnItemChange',
    b'OnModuleAttributeChange',
    b'OnMultiEvent',
    b'orbitID',
    b'ownerID',
    b'ownerName',
    b'quantity',
    b'raceID',
    b'RowClass',
    b'securityStatus',
    b'Sentry Gun',
    b'sessionchange',
    b'singleton',
    b'skillEffect',
    b'squadronID',
    b'typeID',
    b'used',
    b'userID',
    b'util.CachedObject',
    b'util.IndexRowset',
    b'util.Moniker',
    b'util.Row',
    b'util.Rowset',
    b'*multicastID',
    b'AddBalls',
    b'AttackHit3',
    b'AttackHit3R',
    b'AttackHit4R',
    b'DoDestinyUpdates',
    b'GetLocationsEx',
    b'InvalidateCachedObjects',
    b'JoinChannel',
    b'LSC',
    b'LaunchMissile',
    b'LeaveChannel',
    b'OID+',
    b'OID-',
    b'OnAggressionChange',
    b'OnCharGangChange',
    b'OnCharNoLongerInStation',
    b'OnCharNowInStation',
    b'OnDamageMessage',
    b'OnDamageStateChange',
    b'OnEffectHit',
    b'OnGangDamageStateChange',
    b'OnLSC',
    b'OnSpecialFX',
    b'OnTarget',
    b'RemoveBalls',
    b'SendMessage',
    b'SetMaxSpeed',
    b'SetSpeedFraction',
    b'TerminalExplosion',
    b'address',
    b'alert',
    b'allianceID',
    b'allianceid',
    b'bid',
    b'bookmark',
    b'bounty',
    b'channel',
    b'charid',
    b'constellationid',
    b'corpID',
    b'corpid',
    b'corprole',
    b'damage',
    b'duration',
    b'effects.Laser',
    b'gangid',
    b'gangrole',
    b'hqID',
    b'issued',
    b'jit',
    b'languageID',
    b'locationid',
    b'machoVersion',
    b'marketProxy',
    b'minVolume',
    b'orderID',
    b'price',
    b'range',
    b'regionID',
    b'regionid',
    b'role',
    b'rolesAtAll',
    b'rolesAtBase',
    b'rolesAtHQ',
    b'rolesAtOther',
    b'shipid',
    b'sn',
    b'solarSystemID',
    b'solarsystemid',
    b'solarsystemid2',
    b'source',
    b'splash',
    b'stationID',
    b'stationid',
    b'target',
    b'userType',
    b'userid',
    b'volEntered',
    b'volRemaining',
    b'weapon',
    b'agent.missionTemplatizedContent_BasicKillMission',
    b'agent.missionTemplatizedContent_ResearchKillMission',
    b'agent.missionTemplatizedContent_StorylineKillMission',
    b'agent.missionTemplatizedContent_GenericStorylineKillMission',
    b'agent.missionTemplatizedContent_BasicCourierMission',
    b'agent.missionTemplatizedContent_ResearchCourierMission',
    b'agent.missionTemplatizedContent_StorylineCourierMission',
    b'agent.missionTemplatizedContent_GenericStorylineCourierMission',
    b'agent.missionTemplatizedContent_BasicTradeMission',
    b'agent.missionTemplatizedContent_ResearchTradeMission',
    b'agent.missionTemplatizedContent_StorylineTradeMission',
    b'agent.missionTemplatizedContent_GenericStorylineTradeMission',
    b'agent.offerTemplatizedContent_BasicExchangeOffer',
    b'agent.offerTemplatizedContent_BasicExchangeOffer_ContrabandDemand',
    b'agent.offerTemplatizedContent_BasicExchangeOffer_Crafting',
    b'agent.LoyaltyPoints',
    b'agent.ResearchPoints',
    b'agent.Credits',
    b'agent.Item',
    b'agent.Entity',
    b'agent.Objective',
    b'agent.FetchObjective',
    b'agent.EncounterObjective',
    b'agent.DungeonObjective',
    b'agent.TransportObjective',
    b'agent.Reward',
    b'agent.TimeBonusReward',
    b'agent.MissionReferral',
    b'agent.Location',
    b'agent.StandardMissionDetails',
    b'agent.OfferDetails',
    b'agent.ResearchMissionDetails',
    b'agent.StorylineMissionDetails')
